server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/radebit/rade-cloud-config.git
          search-paths:
            - rade-cloud-config
          username: radebit
          password: jys251683
        default-label: master

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka