server:
  port: 3344
spring:
  application:
    name: cloud-config-center # 注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/radebit/rade-cloud-config.git
          default-label: master
          search-paths: /**
  # RabbitMQ相关配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

# 服务注册到Eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

# 暴露监控端点（暴露Bus刷新配置的端点）
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
