server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider-9002
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
