server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh   # 路由ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001    # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/**
        - id: payment_routh2   # 路由ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001    # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/discovery/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true  # 把自己注册进Eureka
    fetch-registry: true  # 是否从EurekaServer抓取已有的注册信息。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka