server:
  port: 7001

# 单机版写法
eureka:
  instance:
    hostname: localhost # eureka服务端的实例名称
  client:
    register-with-eureka: false # false表示不向注册中心注册自己
    fetch-registry: false # false表示自己就是注册中心，职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  # 设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址

# 集群写法
#eureka:
#  instance:
#    hostname: eureka7001.com # eureka服务端的实例名称
#  client:
#    register-with-eureka: false # false表示不向注册中心注册自己
#    fetch-registry: false # false表示自己就是注册中心，职责就是维护服务实例，并不需要去检索服务
#    service-url:
#      defaultZone: http://eureka7002.com:7002/eureka/  # 设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
#  server:
#    enable-self-preservation: false # 自我保护模式，默认开启，这边强制关闭
#    eviction-interval-timer-in-ms: 2000 # 时间间隔