server:
  port: 8401
spring:
  application:
    name: cloud-alibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        # 配置Sentinel Dashboard地址
        dashboard: localhost:5020
        # 默认8719端口，假如被占用自动从8719开始依次+1扫描，直至找到未被占用的端口
        port: 8719
# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
